[package]
name = "strict_encoding"
version = "2.7.0"
description = "Strict encoding: deterministic & confined binary serialization for strict types"
keywords = ["strict-types", "gadt", "serialization", "serde", "protobuf"]
categories = ["encoding", "parsing"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = ["derive", "test_helpers"]

[dependencies]
amplify = { workspace = true, features = ["proc_attr"] }
strict_encoding_derive = { version = "2.7.0", path = "derive" }
half = { version = "~2.2.0", optional = true } # Required to maintain MSRV
serde_crate = { workspace = true, optional = true }

[dev-dependencies]
rand = "0.8.5"
amplify = { workspace = true, features = ["proc_attr", "hex"] }
strict_encoding_test = { version = "2.7.0", path = "./test_helpers" }

[features]
default = [
    "derive"
]
all = [
    "float",
    "derive",
    "serde"
]
derive = []
float = [
    "amplify/apfloat",
    "half"
]
serde = [
    "serde_crate",
    "amplify/serde"
]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
