[package]
name = "strict_encoding"
version = "2.0.0-beta.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@ubideco.org>"]
description = "Strict encoding: deterministic & confined binary serialization for strict types"
repository = "https://github.com/strict-types/strict_encoding"
homepage = "https://strict-encoding.org"
keywords = ["strict-types", "gadt", "serialization", "serde", "protobuf"]
categories = ["encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.65.0" # Due to GAT
exclude = ["derive"]

[dependencies]
amplify = { version = "4.0.0-beta.7", features = ["proc_attr"] }
# strict_encoding_derive = { version = "2.0.0-alpha.1", optional = true }
half = { version = "2.1.0", optional = true }

[dev-dependencies]
rand = "0.8.5"
amplify = { version = "4.0.0-beta.7", features = ["proc_attr", "hex"] }
strict_encoding_test = { version = "2.0.0-alpha.1", path = "./test_helpers" }

[features]
default = [
    "derive"
]
all = [
    "float",
    "derive"
]
derive = [
#    "strict_encoding_derive"
]
float = [
    "amplify/apfloat",
    "half"
]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
